### ISSUE TITLE
Code running issue

### ISSUE THREAD

**Issue by zhangjiadong912** [arnab13061989/Term-Premium#1]
Hey thank you very much for your code

I run the code from the start until I reach this line, the RStudio report error, I didnt change anything on your code, may I know the reason? Thank you!!!

![image](https://user-images.githubusercontent.com/59059788/136946849-b6b60dbb-9c0d-4e78-a877-88bd76f3f642.png)

**Comment by arnab13061989** [comment]
Yes , you will get different results , these are all regression based approach , reducing sample size will introduce further small sample bias , as you will be not observing  complete cycle of interest rates .

**Comment by Rukus8199** [comment]
Hi Arnab,

Thank you very much for your correction, that is very useful, I could run the R code.

However, I have some other codes need to use the ACM calculation in Python environment, may I know if you would also like to publish a Python version of this code?

Thank you very much.
